# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-30 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20161123_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_user_profile_friends_+', to='app01.User_Profile'),
        ),
    ]
